const animalImages = {
  DOG: {
    WHITE: {
      idle: require('./../../assets/images/pets/dog/white/dog_idle.png'),
      face: require('./../../assets/images/pets/dog/white/dog_face.png'),
      hand1: require('./../../assets/images/pets/dog/white/dog_hand1.png'),
      hand2: require('./../../assets/images/pets/dog/white/dog_hand2.png'),
      feed1: require('./../../assets/images/pets/dog/white/dog_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/dog/white/dog_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/dog/white/dog_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/dog/white/dog_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/dog/white/dog_dirty1.png'),
      shower1: require('./../../assets/images/pets/dog/white/dog_dirty2.png'),
      shower2: require('./../../assets/images/pets/dog/white/dog_dirty3.png'),
      clothes: require('./../../assets/images/pets/dog/white/dog_clothes.png'),
      YELLOW: require('./../../assets/images/pets/dog/white/dog_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/dog/white/dog_ribbon_black.png'),
    },
    BROWN: {
      idle: require('./../../assets/images/pets/dog/brown/dog_idle.png'),
      face: require('./../../assets/images/pets/dog/brown/dog_face.png'),
      hand1: require('./../../assets/images/pets/dog/brown/dog_hand1.png'),
      hand2: require('./../../assets/images/pets/dog/brown/dog_hand2.png'),
      feed1: require('./../../assets/images/pets/dog/brown/dog_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/dog/brown/dog_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/dog/brown/dog_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/dog/brown/dog_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/dog/brown/dog_dirty1.png'),
      shower1: require('./../../assets/images/pets/dog/brown/dog_dirty2.png'),
      shower2: require('./../../assets/images/pets/dog/brown/dog_dirty3.png'),
      clothes: require('./../../assets/images/pets/dog/brown/dog_clothes.png'),
      YELLOW: require('./../../assets/images/pets/dog/brown/dog_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/dog/brown/dog_ribbon_black.png'),
    },
    BLACK: {
      idle: require('./../../assets/images/pets/dog/black/dog_idle.png'),
      face: require('./../../assets/images/pets/dog/black/dog_face.png'),
      hand1: require('./../../assets/images/pets/dog/black/dog_hand1.png'),
      hand2: require('./../../assets/images/pets/dog/black/dog_hand2.png'),
      feed1: require('./../../assets/images/pets/dog/black/dog_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/dog/black/dog_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/dog/black/dog_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/dog/black/dog_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/dog/black/dog_dirty1.png'),
      shower1: require('./../../assets/images/pets/dog/black/dog_dirty2.png'),
      shower2: require('./../../assets/images/pets/dog/black/dog_dirty3.png'),
      clothes: require('./../../assets/images/pets/dog/black/dog_clothes.png'),
      YELLOW: require('./../../assets/images/pets/dog/black/dog_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/dog/black/dog_ribbon_black.png'),
    },
    GRAY: {
      idle: require('./../../assets/images/pets/dog/gray/dog_idle.png'),
      face: require('./../../assets/images/pets/dog/gray/dog_face.png'),
      hand1: require('./../../assets/images/pets/dog/gray/dog_hand1.png'),
      hand2: require('./../../assets/images/pets/dog/gray/dog_hand2.png'),
      feed1: require('./../../assets/images/pets/dog/gray/dog_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/dog/gray/dog_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/dog/gray/dog_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/dog/gray/dog_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/dog/gray/dog_dirty1.png'),
      shower1: require('./../../assets/images/pets/dog/gray/dog_dirty2.png'),
      shower2: require('./../../assets/images/pets/dog/gray/dog_dirty3.png'),
      clothes: require('./../../assets/images/pets/dog/gray/dog_clothes.png'),
      YELLOW: require('./../../assets/images/pets/dog/gray/dog_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/dog/gray/dog_ribbon_black.png'),
    },
    YELLOWDARK: {
      idle: require('./../../assets/images/pets/dog/yellow/dog_idle.png'),
      face: require('./../../assets/images/pets/dog/yellow/dog_face.png'),
      hand1: require('./../../assets/images/pets/dog/yellow/dog_hand1.png'),
      hand2: require('./../../assets/images/pets/dog/yellow/dog_hand2.png'),
      feed1: require('./../../assets/images/pets/dog/yellow/dog_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/dog/yellow/dog_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/dog/yellow/dog_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/dog/yellow/dog_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/dog/yellow/dog_dirty1.png'),
      shower1: require('./../../assets/images/pets/dog/yellow/dog_dirty2.png'),
      shower2: require('./../../assets/images/pets/dog/yellow/dog_dirty3.png'),
      clothes: require('./../../assets/images/pets/dog/yellow/dog_clothes.png'),
      YELLOW: require('./../../assets/images/pets/dog/yellow/dog_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/dog/yellow/dog_ribbon_black.png'),
    },
  },
  CAT: {
    WHITE: {
      idle: require('./../../assets/images/pets/cat/white/cat_idle.png'),
      face: require('./../../assets/images/pets/cat/white/cat_face.png'),
      hand1: require('./../../assets/images/pets/cat/white/cat_hand1.png'),
      hand2: require('./../../assets/images/pets/cat/white/cat_hand2.png'),
      feed1: require('./../../assets/images/pets/cat/white/cat_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/cat/white/cat_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/cat/white/cat_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/cat/white/cat_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/cat/white/cat_dirty1.png'),
      shower1: require('./../../assets/images/pets/cat/white/cat_dirty2.png'),
      shower2: require('./../../assets/images/pets/cat/white/cat_dirty3.png'),
      clothes: require('./../../assets/images/pets/cat/white/cat_clothes.png'),
      YELLOW: require('./../../assets/images/pets/cat/white/cat_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/cat/white/cat_ribbon_black.png'),
    },
    BLACK: {
      idle: require('./../../assets/images/pets/cat/black/cat_idle.png'),
      face: require('./../../assets/images/pets/cat/black/cat_face.png'),
      hand1: require('./../../assets/images/pets/cat/black/cat_hand1.png'),
      hand2: require('./../../assets/images/pets/cat/black/cat_hand2.png'),
      feed1: require('./../../assets/images/pets/cat/black/cat_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/cat/black/cat_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/cat/black/cat_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/cat/black/cat_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/cat/black/cat_dirty1.png'),
      shower1: require('./../../assets/images/pets/cat/black/cat_dirty2.png'),
      shower2: require('./../../assets/images/pets/cat/black/cat_dirty3.png'),
      clothes: require('./../../assets/images/pets/cat/black/cat_clothes.png'),
      YELLOW: require('./../../assets/images/pets/cat/black/cat_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/cat/black/cat_ribbon_black.png'),
    },
    GRAY: {
      idle: require('./../../assets/images/pets/cat/gray/cat_idle.png'),
      face: require('./../../assets/images/pets/cat/gray/cat_face.png'),
      hand1: require('./../../assets/images/pets/cat/gray/cat_hand1.png'),
      hand2: require('./../../assets/images/pets/cat/gray/cat_hand2.png'),
      feed1: require('./../../assets/images/pets/cat/gray/cat_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/cat/gray/cat_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/cat/gray/cat_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/cat/gray/cat_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/cat/gray/cat_dirty1.png'),
      shower1: require('./../../assets/images/pets/cat/gray/cat_dirty2.png'),
      shower2: require('./../../assets/images/pets/cat/gray/cat_dirty3.png'),
      clothes: require('./../../assets/images/pets/cat/gray/cat_clothes.png'),
      YELLOW: require('./../../assets/images/pets/cat/gray/cat_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/cat/gray/cat_ribbon_black.png'),
    },
    HALFGRAY: {
      idle: require('./../../assets/images/pets/cat/half_gray/cat_idle.png'),
      face: require('./../../assets/images/pets/cat/half_gray/cat_face.png'),
      hand1: require('./../../assets/images/pets/cat/half_gray/cat_hand1.png'),
      hand2: require('./../../assets/images/pets/cat/half_gray/cat_hand2.png'),
      feed1: require('./../../assets/images/pets/cat/half_gray/cat_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/cat/half_gray/cat_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/cat/half_gray/cat_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/cat/half_gray/cat_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/cat/half_gray/cat_dirty1.png'),
      shower1: require('./../../assets/images/pets/cat/half_gray/cat_dirty2.png'),
      shower2: require('./../../assets/images/pets/cat/half_gray/cat_dirty3.png'),
      clothes: require('./../../assets/images/pets/cat/half_gray/cat_clothes.png'),
      YELLOW: require('./../../assets/images/pets/cat/half_gray/cat_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/cat/half_gray/cat_ribbon_black.png'),
    },
    YELLOWDARK: {
      idle: require('./../../assets/images/pets/cat/yellow/cat_idle.png'),
      face: require('./../../assets/images/pets/cat/yellow/cat_face.png'),
      hand1: require('./../../assets/images/pets/cat/yellow/cat_hand1.png'),
      hand2: require('./../../assets/images/pets/cat/yellow/cat_hand2.png'),
      feed1: require('./../../assets/images/pets/cat/yellow/cat_eat_feed1.png'),
      feed2: require('./../../assets/images/pets/cat/yellow/cat_eat_feed2.png'),
      snack1: require('./../../assets/images/pets/cat/yellow/cat_eat_snack1.png'),
      snack2: require('./../../assets/images/pets/cat/yellow/cat_eat_snack2.png'),
      dirty: require('./../../assets/images/pets/cat/yellow/cat_dirty1.png'),
      shower1: require('./../../assets/images/pets/cat/yellow/cat_dirty2.png'),
      shower2: require('./../../assets/images/pets/cat/yellow/cat_dirty3.png'),
      clothes: require('./../../assets/images/pets/cat/yellow/cat_clothes.png'),
      YELLOW: require('./../../assets/images/pets/cat/yellow/cat_ribbon_yellow.png'),
      BLACK: require('./../../assets/images/pets/cat/yellow/cat_ribbon_black.png'),
    },
  },
};

export default animalImages;
